### ðŸ‘‰ Import required libraries

In [2]:
import pandas as pd

### ðŸ‘‰ define dataframe

In [3]:
df = pd.read_csv(r"./datasets/accident-data.csv")

In [5]:
df.head().style.highlight_max()

In [12]:
def pandas_styling(df):
     return df.style.highlight_max().highlight_min().highlight_null(null_color = 'blue')

In [12]:
pandas_styling(df.isna(subset = [['latitude', 'longitude']]).head())

TypeError: isna() got an unexpected keyword argument 'subset'

In [19]:
df[df[['latitude', 'longitude']].isna() == False]

,accident_index,accident_year,accident_reference,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,NaN,NaN,NaN,-0.254001,51.462262,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,-0.139253,51.470327,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,-0.178719,51.529614,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,-0.001683,51.541210,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,-0.137592,51.515704,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91194,NaN,NaN,NaN,-2.926320,56.473539,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91195,NaN,NaN,NaN,-4.267565,55.802353,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91196,NaN,NaN,NaN,-2.271903,57.186317,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91197,NaN,NaN,NaN,-3.968753,55.950940,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91198,NaN,NaN,NaN,-4.561040,56.003843,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
cols = ['latitude', 'longitude']
pandas_styling(df[df['latitude'].isna()])